DROP DATABASE IF EXISTS sns;
CREATE DATABASE sns;
USE sns;

CREATE TABLE USER (
    User_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Biography TEXT
);

CREATE TABLE POST (
    Post_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    User_id INT NOT NULL,
    File_path VARCHAR(255),
    File_name VARCHAR(255),
    Upload_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    Update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (User_id) REFERENCES USER(User_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE IMAGE (
    Image_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Post_id INT NOT NULL,
    File_path VARCHAR(255),
    File_name VARCHAR(255),
    FOREIGN KEY (Post_id) REFERENCES POST(Post_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE COMMENT (
    Comment_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Post_id INT NOT NULL,
    User_id INT NOT NULL,
    Comment TEXT NOT NULL,
    Upload_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    Update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (Post_id) REFERENCES POST(Post_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (User_id) REFERENCES USER(User_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE LIKE_OR_DISLIKE (
    User_id INT NOT NULL,
    Post_id INT NOT NULL,
    L_or_D ENUM('LIKE','DISLIKE') NOT NULL,
    PRIMARY KEY (User_id, Post_id),
    FOREIGN KEY (User_id) REFERENCES USER(User_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (Post_id) REFERENCES POST(Post_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

SHOW TABLES;
SELECT * from user